services:
  oncopixel:
    build:
      context: .
    container_name: oncopixel_container
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared-network
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./media:/app/media

networks:
  shared-network:
    external: true
